name: Build FunctionApp

on:
  push:
    branches: [ "main", "principal" ]
  pull_request:
    branches: [ "main", "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src
        run: dotnet build --configuration Release --no-restore
